#! /bin/bash

# 
#            --------------------------------------------------
#                            ehtoolslite Framework          
#            --------------------------------------------------
#        Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
#    ehtoolslite framework [based on lscript]
#    
#    
#    About Author :
#    
#    Founder : Entynetproject (Ivan Nikolsky)
#    Instagram : @entynetproject | @ehtools_framework
#    Email : entynetproject@gmail.com
#    Project's site : https://entynethacker.wixsite.com/ehtools
#    Entynetproject's site : http://entynetproject.simplesite.com/
#


clear
printf '\033]2;Modules (BETA)\a'
echo -e "               ____   "
echo -e " Modules      /\___\  "
echo -e " (BETA)      /\ \___\ "
echo -e "  for        \ \/ / / "
echo -e "ehtoolslite   \/_/_/  By Ivan Nikolsky "
sleep 3
echo -e "Welcome to Modules (BETA)"
sleep 1
echo -e "Instrument to add eht modules to /bin"
sleep 1
echo -e "It's fully safely!"
sleep 1
echo -e "Press \e[1;33many key\e[0m to install modules (BETA)"
read -n 1
clear
echo -e "Well, we are going to start!"
sleep 2
echo -e "\e[4;32mPreparing to install...\e[0m"
sleep 1
echo -e "Getting 10%"
sleep 1
echo -e "Getting 15%"
sleep 1
echo -e "Getting 20%"
sleep 1
echo -e "Getting 25%"
sleep 1
echo -e "Getting 30%"
sleep 1
echo -e "Getting 35%"
sleep 1
echo -e "Getting 40%"
sleep 1
echo -e "Getting 45%"
sleep 1
echo -e "Getting 50%"
sleep 1
echo -e "Getting 55%"
sleep 1
echo -e "Getting 60%"
sleep 1
echo -e "Getting 65%"
sleep 1 
echo -e "Getting 70%"
sleep 1
echo -e "Getting 75%"
sleep 1
echo -e "Getting 80%"
sleep 1
echo -e "Getting 85%"
sleep 1
echo -e "Getting 90%"
sleep 1
echo -e "Getting 95%"
sleep 1
echo -e "Getting 100%"
sleep 3
echo -e "10 tar archives installed to /bin with success!"
sleep 2
echo -e " \e[4;32mPreparing to unpack...\e[0m"
sleep 5
echo -e "\e[4;32mSuccess!\e[0m"
sleep 5
chmod +x /root/ehtoolslite/eht1
chmod +x /root/ehtoolslite/eht2
chmod +x /root/ehtoolslite/eht3
chmod +x /root/ehtoolslite/eht21
chmod +x /root/ehtoolslite/eht31
chmod +x /root/ehtoolslite/eht4
chmod +x /root/ehtoolslite/eht41
chmod +x /root/ehtoolslite/eht42
chmod +x /root/ehtoolslite/eht43
sleep 5 
echo -e "Setting up permissions..."
sleep 5
echo -e "Moving ehtoolslite modules to /bin..."
sleep 5
cp /root/ehtoolslite/eht1 /bin/ehtoolslite
cp /root/ehtoolslite/eht2 /bin/ehtoolslite
cp /root/ehtoolslite/eht3 /bin/ehtoolslite
cp /root/ehtoolslite/eht4 /bin/ehtoolslite
cp /root/ehtoolslite/eht21 /bin/ehtoolslite
cp /root/ehtoolslite/eht31 /bin/ehtoolslite
cp /root/ehtoolslite/eht41 /bin/ehtoolslite
cp /root/ehtoolslite/eht42 /bin/ehtoolslite
cp /root/ehtoolslite/eht43 /bin/ehtoolslite
cp /root/ehtools/euh /bin
chmod +x /bin/euh
cp /root/ehtoolslite/eht1 /bin
chmod +x /bin/eht1
cp /root/ehtoolslite/eht2 /bin
chmod +x /bin/eht2
cp /root/ehtoolslite/eht3 /bin
chmod +x /bin/eht3
cp /root/ehtoolslite/eht31 /bin
chmod +x /bin/eht31
cp /root/ehtoolslite/eht4 /bin
chmod +x /bin/eht4
cp /root/ehtoolslite/eht41 /bin
chmod +x /bin/eht41
cp /root/ehtoolslite/eht42 /bin
chmod +x /bin/eht42
cp /root/ehtoolslite/eht43 /bin
chmod +x /bin/eht43
cp /root/ehtoolslite/eht21 /bin
chmod +x /bin/eht21
sleep 5
echo -e "Modules added to /bin with success!"
sleep 1
echo -e "Good job! You can open modules with commands:"
sleep 1
echo -e "> eht1"
sleep 1
echo -e "> eht2"
sleep 1
echo -e "> eht3"
sleep 1
echo -e "> eht4"
sleep 1
echo -e "> eht21"
sleep 1
echo -e "> eht31"
sleep 1
echo -e "> eht41"
sleep 1
echo -e "> eht42"
sleep 1
echo -e "> eht43"
sleep 5
echo -e "read more about this modules on my wiki"
